### ISSUE TITLE
ElementPlusError: [ElPagination] 你使用了一些已被废弃的用法，请参考 el-pagination 的官方文档

### ISSUE THREAD

**Issue by HXM-L** [flowerburied/VUE3-template-back#1]
你好，我在使用el-pagination插件的时候出现使用了 :total="total"这个问题，可以告诉我错误的地方在哪里吗？
![image](https://user-images.githubusercontent.com/49579192/165924726-9d9e495e-5ae0-45ad-9e36-7f3d407e6167.png)
 <el-col :span="24">
          <el-pagination
            @size-change="handleSizeChange"
            @current-change="handleCurrentChange"
            :current-page="currentPage"
            :page-sizes="[100, 200, 300, 400]"
            :page-size="pageSize"
            layout="total, sizes, prev, pager, next, jumper"
            :total="total">
          </el-pagination>
        </el-col>
![image](https://user-images.githubusercontent.com/49579192/165924900-5988171a-6621-411b-8d46-b1b6dbb4ec37.png)

**Comment by yxzlwz** [comment]
同样问题 蹲一下
![image](https://user-images.githubusercontent.com/75941562/168410793-e1cd824d-fee0-4826-bce1-2f6092a8c420.png)
![image](https://user-images.githubusercontent.com/75941562/168410806-790d9cd5-0f8e-4662-8f7b-8b221d53023b.png)

**Comment by Linhongbin-1111** [comment]
同问题，版本 2.1.4，之前一直没问题，没更新版本，今天突然出现的 warning。
甚至很神奇的是，其他页面分页也是相同的用法，没报 warning。
将 @size-change 改为 @update:size-change="" 以及 @current-change 改为 @update：current-page="" 去监听也同样报 warning。
并且此 warning 直接导致组件无法使用，希望尽快更新文档。

**Comment by HXM-L** [comment]
上次问题已解决,导致警告的原因是我调用后台接口,获取返回数据的时候,给前端的total赋值的数据的类型不是int类型,才会出现警告.
![1652682067(1)](https://user-images.githubusercontent.com/49579192/168532292-4a20fde2-d9fe-4945-8853-03bb31537ae8.jpg)

**Comment by Linhongbin-1111** [comment]
> 上次问题已解决,导致警告的原因是我调用后台接口,获取返回数据的时候,给前端的total赋值的数据的类型不对,才会出现警告. if (result.data.success) { this.medicalStafftableData = result.data.objectList; console.log("total:" + result.data.total); this.pageObject.totalRows = result.data.total; if (result.data.objectList == null) { /* 查询记录为空 */ this.$message({ showClose: true, message: result.data.message, type: "warning", }); return false; } } ![1652682067(1)](https://user-images.githubusercontent.com/49579192/168532292-4a20fde2-d9fe-4945-8853-03bb31537ae8.jpg)

好的非常感谢！ @HXM-L

**Comment by MUkkm** [comment]
https://github.com/flowerburied/VUE3-template-back/issues/1#issuecomment-1127270628 确实是这个问题哈

**Comment by yxzlwz** [comment]
https://github.com/flowerburied/VUE3-template-back/issues/1#issuecomment-1127270628 

我也是这样，后端返回数据异常了导致 total 不是 int

**Comment by shan-shang** [comment]
thanks

> > 上次问题已解决,导致警告的原因是我调用后台接口,获取返回数据的时候,给前端的total赋值的数据的类型不对,才会出现警告. if (result.data.success) { this.medicalStafftableData = result.data.objectList; console.log("total:" + result.data.total); this.pageObject.totalRows = result.data.total; if (result.data.objectList == null) { /* 查询记录为空 */ this.$message({ showClose: true, message: result.data.message, type: "warning", }); return false; } } ![1652682067(1)](https://user-images.githubusercontent.com/49579192/168532292-4a20fde2-d9fe-4945-8853-03bb31537ae8.jpg)
> 
> 好的非常感谢！ @HXM-L



> 上次问题已解决,导致警告的原因是我调用后台接口,获取返回数据的时候,给前端的total赋值的数据的类型不是int类型,才会出现警告. ![1652682067(1)](https://user-images.githubusercontent.com/49579192/168532292-4a20fde2-d9fe-4945-8853-03bb31537ae8.jpg)

thanks for you

**Comment by shan-shang** [comment]
> 上次问题已解决,导致警告的原因是我调用后台接口,获取返回数据的时候,给前端的total赋值的数据的类型不是int类型,才会出现警告. ![1652682067(1)](https://user-images.githubusercontent.com/49579192/168532292-4a20fde2-d9fe-4945-8853-03bb31537ae8.jpg)

thanks

**Comment by oknixus** [comment]
同样遇到这个问题，也是同样的代码，在别的地方无此错误。
查了很久，也检查代码中total的类型，确定是number无误，但是就是会提示这个错误；
而且也只能用`:total="Number(total)"才不会再提示这个错误。如果是在获取数据后，使用`parseInt(total)`或`Number(total)`都会报此错误

**Comment by flowerburied** [comment]
Readme 早就写了  用数字的就不能用字符串 两年前的项目了别√8挖坟了
